spring.application.name=sql-intro

spring.datasource.url=jdbc:postgresql://localhost:8585/postgres
spring.datasource.username=postgres
spring.datasource.password=*


spring.jpa.hibernate.ddl-auto=update
